version: '3.9'

services:
  postgres:
    container_name: postgres_flask_ligand_example
    image: postgres:10-alpine
    volumes:
      - ./docker/db-data/:/var/lib/postgresql/data/
      - ./docker/postgres-data/:/docker-entrypoint-initdb.d/
    env_file:
      - docker/env_files/integration.env
    ports:
      - '5432:5432'
    networks:
      - backend
    hostname: postgres_flask_ligand_example

  keycloak:
    container_name: keycloak_flask_ligand_example
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./docker/kc-data/:/opt/keycloak/data/import/
    env_file:
      - docker/env_files/integration.env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - backend
    command: start-dev --import-realm

  openapi:
    container_name: openapi_flask_ligand_example
    image: openapitools/openapi-generator-online:v6.1.0
    ports:
      - '8888:8080'
    command: java -Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true -jar /generator/openapi-generator-online.jar

networks:
  backend:
    name: backend
    driver: bridge
